#pragma once

namespace Halley {} // Get GitHub to realise this is C++ :3

#include "ui_anchor.h"
#include "ui_behaviour.h"
#include "ui_colour_scheme.h"
#include "ui_data_bind.h"
#include "ui_element.h"
#include "ui_event.h"
#include "ui_event_handler.h"
#include "ui_factory.h"
#include "ui_factory_tester.h"
#include "ui_input.h"
#include "ui_root.h"
#include "ui_sizer.h"
#include "ui_style.h"
#include "ui_stylesheet.h"
#include "ui_validator.h"
#include "ui_widget.h"

#include "behaviours/ui_transition_slide_behaviour.h"
#include "behaviours/ui_reload_ui_behaviour.h"

#include "widgets/ui_animation.h"
#include "widgets/ui_button.h"
#include "widgets/ui_checkbox.h"
#include "widgets/ui_debug_console.h"
#include "widgets/ui_dropdown.h"
#include "widgets/ui_framed_image.h"
#include "widgets/ui_gamepad_image.h"
#include "widgets/ui_hybrid_list.h"
#include "widgets/ui_image.h"
#include "widgets/ui_label.h"
#include "widgets/ui_list.h"
#include "widgets/ui_menu_button.h"
#include "widgets/ui_paged_pane.h"
#include "widgets/ui_popup_menu.h"
#include "widgets/ui_scroll_pane.h"
#include "widgets/ui_scrollbar.h"
#include "widgets/ui_scrollbar_pane.h"
#include "widgets/ui_slider.h"
#include "widgets/ui_spin_control.h"
#include "widgets/ui_spin_control2.h"
#include "widgets/ui_textinput.h"
#include "widgets/ui_tooltip.h"
#include "widgets/ui_tree_list.h"
