#ifdef __cplusplus
#include <string>
#include <algorithm>
#include <vector>
#include <map>
#include <set>
#include <array>
#include <charconv>
#include <gsl/gsl>
#include <cstddef>
#include <limits>
#include <memory>
#include <chrono>
#include <thread>
#include <mutex>
#include <iomanip>
#include <optional>
#include <atomic>
#include <deque>
#include <iostream>
#include <sstream>
#include <istream>
#include <ostream>
#endif
